services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WorldDirect\Healthcheck\:
    resource: "../Classes/*"

  # In order for dependecy injection to work
  WorldDirect\Healthcheck\Middleware\HealthcheckMiddleware:
    public: true
  WorldDirect\Healthcheck\Middleware\ProbePauseMiddleware:
    public: true
  WorldDirect\Healthcheck\Domain\Repository\ProbePauseRepository:
    public: true
  WorldDirect\Healthcheck\Utility\HealthcheckUtility:
    public: true
  
  # System information provider for adding the Healthcheck link
  WorldDirect\Healthcheck\SystemInformation\ToolbarItemProvider:
    tags:
      - name: event.listener
        identifier: 'healthcheck/show-healthcheck-link'
        method: 'getHealthcheckLink'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent
