services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WorldDirect\Healthcheck\:
    resource: "../Classes/*"

  # In order for dependecy injection to work
  WorldDirect\Healthcheck\Middleware\HealthcheckMiddleware:
    public: true
